"""
sector.py — Individual sector / department state.

Each Sector holds its baseline plus transient per-round state
(demand, thresholds, allocation, revenue factor, revenue, consumption).
The game orchestrator resets per-round fields each step.
"""

from __future__ import annotations

from dataclasses import dataclass, field

from .revenue import compute_thresholds, revenue_factor


@dataclass
class Sector:
    """Mutable state for one government department."""

    # ── Identity (set once at episode start) ────────────────────
    name: str
    baseline: float
    full_name: str = ""
    description: str = ""

    # ── Per-round computed state ────────────────────────────────
    event_multiplier: float = 1.0

    demand: float = 0.0
    critical: float = 0.0
    surplus: float = 0.0
    wastage: float = 0.0

    allocation: float = 0.0
    revenue_factor_value: float = 0.0
    revenue: float = 0.0
    consumption: float = 0.0

    # ── Config ratios (injected from GameConfig) ────────────────
    _critical_ratio: float = field(default=0.4, repr=False)
    _surplus_ratio: float = field(default=1.5, repr=False)
    _wastage_ratio: float = field(default=2.5, repr=False)
    _rf_max: float = field(default=1.8, repr=False)

    # ── Lifecycle ───────────────────────────────────────────────

    def reset_round(self) -> None:
        """Clear transient state before a new round."""
        self.event_multiplier = 1.0
        self.allocation = 0.0
        self.revenue_factor_value = 0.0
        self.revenue = 0.0
        self.consumption = 0.0

    def update_thresholds(self, population: int, pop_0: int) -> None:
        """Recalculate demand/critical/surplus/wastage for this round."""
        self.critical, self.demand, self.surplus, self.wastage = compute_thresholds(
            baseline=self.baseline,
            population=population,
            pop_0=pop_0,
            event_multiplier=self.event_multiplier,
            critical_ratio=self._critical_ratio,
            surplus_ratio=self._surplus_ratio,
            wastage_ratio=self._wastage_ratio,
        )

    def compute_revenue(self, allocation: float, productivity: float) -> float | None:
        """
        Set allocation, compute revenue factor and revenue.

        Returns
        -------
        float
            Revenue generated by this sector.
        None
            If allocation is below the critical threshold (episode must end).
        """
        self.allocation = allocation

        rf = revenue_factor(
            x=allocation,
            critical=self.critical,
            demand=self.demand,
            surplus=self.surplus,
            wastage=self.wastage,
            rf_max=self._rf_max,
        )

        if rf is None:
            self.revenue_factor_value = 0.0
            self.revenue = 0.0
            return None  # CRITICAL FAILURE

        self.revenue_factor_value = rf
        self.revenue = allocation * rf * productivity
        return self.revenue

    def compute_consumption(self) -> float:
        """
        Consumption = min(allocation, demand).
        Surplus (allocation - consumption) will be returned to treasury.

        Returns the surplus amount.
        """
        self.consumption = min(self.allocation, self.demand)
        return self.allocation - self.consumption  # surplus

    # ── Serialisation helpers ───────────────────────────────────

    def to_dict(self) -> dict:
        """Snapshot of sector state for observations / logging."""
        return {
            "name": self.name,
            "full_name": self.full_name,
            "baseline": self.baseline,
            "demand": round(self.demand, 4),
            "critical": round(self.critical, 4),
            "surplus": round(self.surplus, 4),
            "wastage": round(self.wastage, 4),
            "allocation": round(self.allocation, 4),
            "revenue_factor": round(self.revenue_factor_value, 6),
            "revenue": round(self.revenue, 4),
            "consumption": round(self.consumption, 4),
            "event_multiplier": round(self.event_multiplier, 4),
        }

    @classmethod
    def from_config(cls, name: str, info: dict, config) -> "Sector":
        """Build a Sector from sectors.json data + a GameConfig."""
        return cls(
            name=name,
            baseline=info["baseline"] if isinstance(info, dict) else info,
            full_name=(info.get("full_name", name) if isinstance(info, dict) else name),
            description=(info.get("description", "") if isinstance(info, dict) else ""),
            _critical_ratio=config.CRITICAL_RATIO,
            _surplus_ratio=config.SURPLUS_RATIO,
            _wastage_ratio=config.WASTAGE_RATIO,
            _rf_max=config.RF_MAX,
        )
